### ISSUE TITLE
ALB is not waiting for Internet gateway to be created 

### ISSUE THREAD

**Issue by grepit** [aws-samples/cognito-device-grant-flow#3]
ALB is not waiting for Internet gateway to be created by adding the new line, it worked!

  DeviceGrantALB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !Ref DeviceGrantALBSG
      Subnets:
        - !Ref DeviceGrantPublicSubnet1
        - !Ref DeviceGrantPublicSubnet2
    DependsOn: DeviceGrantInternetGateway    <-------- new
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 00c1e791-1793-45b8-a5e4-1fc6d277b572
  GrantDeviceALBCognitoClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:

**Comment by jeffsec-aws** [comment]
This has been solved in the last CFT template version.

Thanks for the feedback
